Use go-sdk v0.3.7
signadot/cli pull request #36
Opened 2023-03-21 23:56 UTC by jmsktm

2023-03-21 23:59 UTC, foxish commented
The field name changes don't result in some additional changes here to the models in use etc?

2023-03-22 00:00 UTC, jmsktm commented
> The field name changes don't result in some additional changes to the models in use etc? Just the dependency bump will suffice?

Yes. The content from the file will just map to the corresponding types referenced by the new version.

2023-03-22 00:03 UTC, foxish requested changes
LGTM

2023-03-22 00:03 UTC, foxish approved these changes

2023-03-22 00:04 UTC, merged